# Generated by Django 5.2.3 on 2025-09-10 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30)),
                ('delivery', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Complete', 'Complete'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled')], default='Order Processing', max_length=100)),
                ('payment_complite', models.BooleanField(blank=True, default=False, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
