# Generated by Django 5.2.3 on 2025-09-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_complite',
        ),
    ]
