# Generated by Django 5.2.3 on 2025-09-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_order_payment_complite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='01700000000', max_length=16),
        ),
    ]
