# Generated by Django 5.2.3 on 2025-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_mobile_order_last_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Cash on delivery'),
        ),
    ]
