# Generated by Django 5.2.3 on 2025-09-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
