# Generated by Django 5.2.3 on 2025-09-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
