# Generated by Django 5.2.3 on 2025-09-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_image_specialoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='food/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(default=1, upload_to='food/images'),
            preserve_default=False,
        ),
    ]
