# Generated by Django 5.2.3 on 2025-09-06 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.category'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='before_price',
            field=models.IntegerField(),
        ),
    ]
