# Generated by Django 5.2.3 on 2025-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_item_category_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(upload_to='food/images/'),
        ),
    ]
