# Generated by Django 5.2.3 on 2025-09-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_specialoffer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('review_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('review_date', models.DateField()),
            ],
        ),
    ]
