# Generated by Django 5.2.3 on 2025-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
