# Generated by Django 5.2.3 on 2025-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_specialoffer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='id1',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
